config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cities do
    member do
      post :update_temp
    end
  end

  namespace :api, :default => {:format => :json} do
    namespace :v1 do
      get "/trains" => 'trains#index', :as => :trains
      get "/trains/:train_number" => 'trains#show', :as => :train

      get "/reservations/:booking_code", to: 'reservations#show', as: :reservation
      post "/reservations", to: 'reservations#create', as: :create_reservations
      patch "/reservations/:booking_code", to: 'reservations#update', as: :update_reservation
      delete "/reservations/:booking_code", to: 'reservations#destroy', as: :cancel_reservation
      get '/reservations' => "reservations#index", as: :reservations

      post "/signup" => "auth#signup"
      post "/login" => 'auth#login'
      post '/logout' => 'auth#logout'

      get '/me' => 'users#show', :as => :user
      patch '/me' => 'users#update', :as => :update_user
    end
  end

  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
  end

  def update_temp
    city = City.find(params[:id])

    # response = RestClient.get "http://v.juhe.cn/weather/index?format=2&cityname=%E8%8B%8F%E5%B7%9E&key=214b163d003a4799cb76359b6d30b7de"
    response = RestClient.get "http://v.juhe.cn/weather/index",
                          :params => { :cityname => city.juhe_id, :key => JUHE_CONFIG["api_key"] }
    data = JSON.parse(response.body)
    city.update( :current_temp => data["result"]["sk"]["temp"])
    redirect_to cities_path
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Juhe ID</th>
      <th>province</th>
      <th>city</th>
      <th>District</th>
      <th>Temp</th>
    </tr>
  </thead>
  <% @cities.each do |city| %>
    <tr>
      <td><%= city.juhe_id %></td>
      <td><%= city.province %></td>
      <td><%= city.city %></td>
      <td><%= city.district %></td>
      <td>
        <%= city.current_temp %> |
        <%= link_to "更新温度", update_temp_city_path(city), method: :post%>
      </td>
    </tr>
  <% end %>
</tabLe>